---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'VPC: public and private subnets'

Resources:
  VPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: 10.10.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
      Tags:
      - Key: Name
#This will substitute the stack name you supplied while running the template
        Value: !Sub '${AWS::StackName}-VPC'

  InternetGateway:
    Type: 'AWS::EC2::InternetGateway'
    Properties:
      Tags:
      - Key: Name
        Value: !Sub '${AWS::StackName}-InternetGateway'

  VPCGatewayAttachment:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
#Ref is using the ID that gets created during the VPC creation for the VPC ID
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  SubnetPublic:
    Type: 'AWS::EC2::Subnet'
    Properties:
      AvailabilityZone: us-west-2a
      CidrBlock: 10.10.2.0/20
      MapPublicIpOnLaunch: true
      VpcId: !Ref VPC
      Tags:
      - Key: Name
        Value: !Sub '${AWS::StackName}-PublicSubnet'
 
Outputs:
  VPC:
    Description: 'VPC'
    Value: !Ref VPC
    Export:
      Name: !Sub '${AWS::StackName}-VPC'
  SubnetsPublic:
    Description: 'Public Subnet'
    Value: !Sub '${AWS::StackName}-PublicSubnet'
    Export:
      Name: !Sub '${AWS::StackName}-PublicSubnet'
